"""make_artifact_type_string

Revision ID: 26096a455d1d
Revises: ec3162bbe9b9
Create Date: 2026-07-17 22:07:31.049112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26096a455d1d'
down_revision: Union[str, Sequence[str], None] = 'ec3162bbe9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifacts', 'artifact_type',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifacts', 'artifact_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
