"""add_requirements_to_artifact_type_enum

Revision ID: ec3162bbe9b9
Revises: 
Create Date: 2026-07-17 21:51:49.625217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec3162bbe9b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifacts', 'artifact_type',
               existing_type=postgresql.ENUM('spec', 'plan', 'task', name='artifact_type_enum'),
               type_=sa.Enum('spec', 'plan', 'task', 'constitution', 'contract', 'requirements', name='artifact_type_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('doc_versions', 'generated_by',
               existing_type=postgresql.ENUM('agent', 'user', name='generated_by_enum'),
               type_=sa.Enum('agent', 'user', name='generated_by_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('pipeline_runs', 'current_stage',
               existing_type=postgresql.ENUM('parsing', 'parallel_enrichment', 'writing', 'layout', 'rendering', 'completed', 'failed', name='pipeline_stage_enum'),
               type_=sa.Enum('parsing', 'parallel_enrichment', 'writing', 'layout', 'rendering', 'completed', 'failed', name='pipeline_stage_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_runs', 'current_stage',
               existing_type=sa.Enum('parsing', 'parallel_enrichment', 'writing', 'layout', 'rendering', 'completed', 'failed', name='pipeline_stage_enum', native_enum=False),
               type_=postgresql.ENUM('parsing', 'parallel_enrichment', 'writing', 'layout', 'rendering', 'completed', 'failed', name='pipeline_stage_enum'),
               existing_nullable=False)
    op.alter_column('doc_versions', 'generated_by',
               existing_type=sa.Enum('agent', 'user', name='generated_by_enum', native_enum=False),
               type_=postgresql.ENUM('agent', 'user', name='generated_by_enum'),
               existing_nullable=False)
    op.alter_column('artifacts', 'artifact_type',
               existing_type=sa.Enum('spec', 'plan', 'task', 'constitution', 'contract', 'requirements', name='artifact_type_enum', native_enum=False),
               type_=postgresql.ENUM('spec', 'plan', 'task', name='artifact_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
